GROUP=sk.ainet.app
VERSION_NAME=0.8.3

POM_DESCRIPTION=SKaiNET Kotlin Notebook

POM_URL=https://github.com/SKaiNET-developers/skainet-notebook
POM_SCM_URL=https://github.com/SKaiNET-developers/skainet-notebook
POM_SCM_CONNECTION=scm:git:git@github.com:SKaiNET-developers/skainet-notebook.git
POM_SCM_DEV_CONNECTION=scm:git:ssh@github.com:SKaiNET-developers/skainet-notebook.git

POM_LICENCE_NAME=MIT License
POM_LICENCE_URL=https://mit-license.org/
POM_LICENCE_DIST=repo

POM_DEVELOPER_ID=SKaiNET-developers
POM_DEVELOPER_NAME=SKaiNET development team
POM_DEVELOPER_URL=https://github.com/SKaiNET-developers/

mavenCentralPublishing=true
mavenCentralAutomaticPublishing=true
signAllPublications=true


#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.caching=true
# Jupyter Gradle plugin currently incompatible with configuration cache during tests
org.gradle.configuration-cache=false
#Kotlin
kotlin.code.style=official
#MPP
kotlin.mpp.enableCInteropCommonization=true
#Android
android.useAndroidX=true
android.nonTransitiveRClass=true


kotlin.mpp.stability.nowarn=true

SONATYPE_HOST=DEFAULT
SONATYPE_AUTOMATIC_RELEASE=false
RELEASE_SIGNING_ENABLED=false